package ai.gargantua.bundle;

import java.io.Serial;

/**
 * Raised when a bundle or its manifest is malformed, unreadable, or fails integrity
 * verification.
 *
 * <p>Messages carry the offending location in dotted-path form — for example
 * {@code spec.mcp.servers[0].transport} — because a bundle is usually generated by the
 * Studio, and a person debugging one is reading YAML rather than code.</p>
 */
public class BundleException extends RuntimeException {

    @Serial
    private static final long serialVersionUID = 1L;

    public BundleException(String message) {
        super(message);
    }

    public BundleException(String message, Throwable cause) {
        super(message, cause);
    }

    /** Builds a message anchored at a manifest location. */
    public static BundleException at(String path, String problem) {
        return new BundleException(path + ": " + problem);
    }
}
