package ai.gargantua.bundle;

import ai.gargantua.core.capability.Capability;
import ai.gargantua.core.mcp.McpAuth;
import ai.gargantua.core.mcp.McpServerSpec;
import ai.gargantua.core.mcp.McpTransport;
import ai.gargantua.core.memory.MemoryLayer;
import ai.gargantua.core.workload.AgentSpec;
import ai.gargantua.core.workload.ModelSpec;
import ai.gargantua.core.workload.RuntimeSpec;
import ai.gargantua.core.workload.WorkloadKind;
import ai.gargantua.core.workload.WorkloadManifest;
import ai.gargantua.core.workload.WorkloadMetadata;
import org.yaml.snakeyaml.Yaml;

import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;

/**
 * Reads a {@code manifest.yaml} into a {@link WorkloadManifest}.
 *
 * <p>Parsing is explicit rather than reflective binding. The domain records validate
 * themselves in their constructors and the spec type is sealed, so a hand-written parser
 * both keeps that validation meaningful and can report the exact YAML location of a
 * problem — which matters because manifests are read and debugged by people, not only
 * generated by the Studio.</p>
 *
 * @see WorkloadManifest
 */
public final class ManifestParser {

    private ManifestParser() {}

    /** Parses a manifest from a file. */
    public static WorkloadManifest parse(Path file) {
        try {
            return parse(Files.readString(file, StandardCharsets.UTF_8));
        } catch (IOException e) {
            throw new BundleException("Cannot read manifest at " + file + ": " + e.getMessage(), e);
        }
    }

    /** Parses a manifest from a stream. The stream is not closed. */
    public static WorkloadManifest parse(InputStream input) {
        return parse(new String(readAll(input), StandardCharsets.UTF_8));
    }

    /** Parses a manifest from YAML text. */
    public static WorkloadManifest parse(String yaml) {
        if (yaml == null || yaml.isBlank()) {
            throw new BundleException("Manifest is empty");
        }
        Object loaded;
        try {
            loaded = new Yaml().load(yaml);
        } catch (Exception e) {
            throw new BundleException("Manifest is not valid YAML: " + e.getMessage(), e);
        }
        if (!(loaded instanceof Map<?, ?> root)) {
            throw new BundleException("Manifest must be a YAML mapping at the top level");
        }
        Map<String, Object> document = asMap(root, "manifest");

        String apiVersion = string(document, "apiVersion", "apiVersion");
        WorkloadKind kind = kind(document);
        WorkloadMetadata metadata = metadata(map(document, "metadata", "metadata"));

        if (kind != WorkloadKind.AGENT) {
            throw BundleException.at("kind",
                    "workload type " + kind + " is not executable by this runtime yet");
        }
        AgentSpec spec = agentSpec(map(document, "spec", "spec"));

        try {
            return new WorkloadManifest(apiVersion, kind, metadata, spec);
        } catch (IllegalArgumentException e) {
            throw new BundleException(e.getMessage(), e);
        }
    }

    private static WorkloadKind kind(Map<String, Object> document) {
        String raw = string(document, "kind", "kind");
        if (raw == null || raw.isBlank()) {
            throw BundleException.at("kind", "is required");
        }
        try {
            return WorkloadKind.valueOf(raw.trim().toUpperCase(Locale.ROOT).replace('-', '_'));
        } catch (IllegalArgumentException e) {
            throw BundleException.at("kind", "unknown workload kind '" + raw + "'");
        }
    }

    private static WorkloadMetadata metadata(Map<String, Object> metadata) {
        if (metadata == null) {
            throw BundleException.at("metadata", "is required");
        }
        try {
            return new WorkloadMetadata(
                    string(metadata, "name", "metadata.name"),
                    string(metadata, "version", "metadata.version"),
                    string(metadata, "description", "metadata.description"),
                    string(metadata, "owner", "metadata.owner"),
                    stringMap(metadata, "labels", "metadata.labels"));
        } catch (IllegalArgumentException e) {
            throw new BundleException(e.getMessage(), e);
        }
    }

    private static AgentSpec agentSpec(Map<String, Object> spec) {
        if (spec == null) {
            throw BundleException.at("spec", "is required");
        }
        try {
            return new AgentSpec(
                    runtimeSpec(map(spec, "runtime", "spec.runtime")),
                    capabilities(list(spec, "capabilities", "spec.capabilities")),
                    modelSpec(map(spec, "model", "spec.model")),
                    mcpServers(spec),
                    memoryLayers(list(spec, "memoryLayers", "spec.memoryLayers")),
                    string(spec, "defaultSkill", "spec.defaultSkill"),
                    map(spec, "guardrails", "spec.guardrails"),
                    new LinkedHashSet<>(stringList(spec, "allowedRoles", "spec.allowedRoles")));
        } catch (IllegalArgumentException e) {
            throw new BundleException(e.getMessage(), e);
        }
    }

    private static RuntimeSpec runtimeSpec(Map<String, Object> runtime) {
        if (runtime == null) {
            return RuntimeSpec.platformDefault();
        }
        return new RuntimeSpec(
                string(runtime, "image", "spec.runtime.image"),
                string(runtime, "minVersion", "spec.runtime.minVersion"));
    }

    private static ModelSpec modelSpec(Map<String, Object> model) {
        if (model == null) {
            return ModelSpec.inherit();
        }
        return new ModelSpec(
                string(model, "primary", "spec.model.primary"),
                string(model, "fallback", "spec.model.fallback"),
                string(model, "routing", "spec.model.routing"),
                decimal(model, "temperature", "spec.model.temperature"),
                integer(model, "maxTokens", "spec.model.maxTokens"));
    }

    private static List<Capability> capabilities(List<Object> raw) {
        if (raw == null) {
            return List.of();
        }
        List<Capability> capabilities = new ArrayList<>();
        for (int i = 0; i < raw.size(); i++) {
            String path = "spec.capabilities[" + i + "]";
            Map<String, Object> entry = asMap(raw.get(i), path);
            String name = string(entry, "name", path + ".name");
            if (name == null || name.isBlank()) {
                throw BundleException.at(path + ".name", "is required");
            }
            capabilities.add(new Capability(
                    name,
                    string(entry, "description", path + ".description"),
                    string(entry, "version", path + ".version"),
                    string(entry, "inputSchema", path + ".inputSchema"),
                    string(entry, "outputSchema", path + ".outputSchema"),
                    string(entry, "implementedBy", path + ".implementedBy"),
                    new LinkedHashSet<>(stringList(entry, "tags", path + ".tags"))));
        }
        return capabilities;
    }

    private static List<McpServerSpec> mcpServers(Map<String, Object> spec) {
        Map<String, Object> mcp = map(spec, "mcp", "spec.mcp");
        if (mcp == null) {
            return List.of();
        }
        List<Object> raw = list(mcp, "servers", "spec.mcp.servers");
        if (raw == null) {
            return List.of();
        }
        List<McpServerSpec> servers = new ArrayList<>();
        for (int i = 0; i < raw.size(); i++) {
            String path = "spec.mcp.servers[" + i + "]";
            Map<String, Object> entry = asMap(raw.get(i), path);
            try {
                servers.add(new McpServerSpec(
                        string(entry, "name", path + ".name"),
                        transport(entry, path),
                        string(entry, "command", path + ".command"),
                        stringList(entry, "args", path + ".args"),
                        stringMap(entry, "env", path + ".env"),
                        string(entry, "url", path + ".url"),
                        auth(map(entry, "auth", path + ".auth"), path),
                        new LinkedHashSet<>(stringList(entry, "allowedTools", path + ".allowedTools")),
                        bool(entry, "enabled", path + ".enabled", true)));
            } catch (IllegalArgumentException e) {
                throw new BundleException(e.getMessage(), e);
            }
        }
        return servers;
    }

    private static McpTransport transport(Map<String, Object> entry, String path) {
        String raw = string(entry, "transport", path + ".transport");
        if (raw == null || raw.isBlank()) {
            throw BundleException.at(path + ".transport", "is required");
        }
        try {
            return McpTransport.valueOf(raw.trim().toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException e) {
            throw BundleException.at(path + ".transport", "unknown transport '" + raw + "'");
        }
    }

    private static McpAuth auth(Map<String, Object> auth, String path) {
        if (auth == null) {
            return McpAuth.none();
        }
        return new McpAuth(
                string(auth, "type", path + ".auth.type"),
                string(auth, "value", path + ".auth.value"),
                string(auth, "headerName", path + ".auth.headerName"));
    }

    private static Set<MemoryLayer> memoryLayers(List<Object> raw) {
        if (raw == null || raw.isEmpty()) {
            return Set.of();
        }
        Set<MemoryLayer> layers = new LinkedHashSet<>();
        for (Object value : raw) {
            if (value == null) {
                continue;
            }
            try {
                layers.add(MemoryLayer.valueOf(value.toString().trim().toUpperCase(Locale.ROOT)));
            } catch (IllegalArgumentException e) {
                throw BundleException.at("spec.memoryLayers", "unknown memory layer '" + value + "'");
            }
        }
        return layers;
    }

    // ── typed extraction helpers ────────────────────────────────────────────

    private static String string(Map<String, Object> source, String key, String path) {
        Object value = source.get(key);
        if (value == null) {
            return null;
        }
        if (value instanceof Map || value instanceof List) {
            throw BundleException.at(path, "expected a scalar value");
        }
        return value.toString();
    }

    private static Integer integer(Map<String, Object> source, String key, String path) {
        Object value = source.get(key);
        if (value == null) {
            return null;
        }
        if (value instanceof Number number) {
            return number.intValue();
        }
        try {
            return Integer.valueOf(value.toString().trim());
        } catch (NumberFormatException e) {
            throw BundleException.at(path, "expected an integer, got '" + value + "'");
        }
    }

    private static Double decimal(Map<String, Object> source, String key, String path) {
        Object value = source.get(key);
        if (value == null) {
            return null;
        }
        if (value instanceof Number number) {
            return number.doubleValue();
        }
        try {
            return Double.valueOf(value.toString().trim());
        } catch (NumberFormatException e) {
            throw BundleException.at(path, "expected a number, got '" + value + "'");
        }
    }

    private static boolean bool(Map<String, Object> source, String key, String path, boolean fallback) {
        Object value = source.get(key);
        if (value == null) {
            return fallback;
        }
        if (value instanceof Boolean flag) {
            return flag;
        }
        String text = value.toString().trim();
        if ("true".equalsIgnoreCase(text)) return true;
        if ("false".equalsIgnoreCase(text)) return false;
        throw BundleException.at(path, "expected true or false, got '" + value + "'");
    }

    private static Map<String, Object> map(Map<String, Object> source, String key, String path) {
        Object value = source.get(key);
        if (value == null) {
            return null;
        }
        return asMap(value, path);
    }

    @SuppressWarnings("unchecked")
    private static List<Object> list(Map<String, Object> source, String key, String path) {
        Object value = source.get(key);
        if (value == null) {
            return null;
        }
        if (!(value instanceof List)) {
            throw BundleException.at(path, "expected a list");
        }
        return (List<Object>) value;
    }

    private static List<String> stringList(Map<String, Object> source, String key, String path) {
        List<Object> raw = list(source, key, path);
        if (raw == null) {
            return List.of();
        }
        List<String> values = new ArrayList<>(raw.size());
        for (Object value : raw) {
            if (value != null) {
                values.add(value.toString());
            }
        }
        return values;
    }

    private static Map<String, String> stringMap(Map<String, Object> source, String key, String path) {
        Map<String, Object> raw = map(source, key, path);
        if (raw == null) {
            return Map.of();
        }
        Map<String, String> values = new LinkedHashMap<>();
        raw.forEach((entryKey, value) -> values.put(entryKey, value == null ? "" : value.toString()));
        return values;
    }

    @SuppressWarnings("unchecked")
    private static Map<String, Object> asMap(Object value, String path) {
        if (!(value instanceof Map<?, ?> map)) {
            throw BundleException.at(path, "expected a mapping");
        }
        Map<String, Object> typed = new LinkedHashMap<>();
        for (Map.Entry<?, ?> entry : map.entrySet()) {
            typed.put(String.valueOf(entry.getKey()), entry.getValue());
        }
        return typed;
    }

    private static byte[] readAll(InputStream input) {
        try {
            return input.readAllBytes();
        } catch (IOException e) {
            throw new BundleException("Cannot read manifest: " + e.getMessage(), e);
        }
    }
}
