package ai.gargantua.core.cost;

/**
 * Event emitted after each LLM call for cost tracking and billing.
 * Persisted by the {@code CostTracker} when cost tracking is enabled.
 *
 * @param userId       who initiated the request
 * @param sessionId    conversation session
 * @param skillName    the activated skill
 * @param provider     LLM provider name (e.g. "openai", "anthropic")
 * @param model        model identifier (e.g. "gpt-4o")
 * @param phase        pipeline phase ("main", "routing", "summarizer")
 * @param inputTokens  tokens consumed by the prompt
 * @param outputTokens tokens generated by the model
 * @param durationMs   wall-clock time of the LLM call
 * @param dryRun       whether this was a dry-run (no real cost incurred)
 */
public record CostTrackingEvent(
        String userId,
        String sessionId,
        String skillName,
        String provider,
        String model,
        String phase,
        int inputTokens,
        int outputTokens,
        long durationMs,
        boolean dryRun
) {
}
