apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gargantua-parent
  labels:
    app.kubernetes.io/name: gargantua-parent
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gargantua-parent
