apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gargantua-parent
  labels:
    app.kubernetes.io/name: gargantua-parent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gargantua-parent
  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s
      scrapeTimeout: 10s
  namespaceSelector:
    matchNames:
      - default
